version: '3.8'

services:
  server:
    build: ./server
    container_name: keep-server
    ports:
      - "3500:3000"
    volumes:
      - osckeep-data:/app/data
    restart: always

  web:
    build: ./web
    container_name: keep-web
    ports:
      - "9091:80"
    depends_on:
      - server
    restart: always

volumes:
  osckeep-data:
